### ISSUE TITLE
Syntax Issues with last version - Blocking Serverless

### ISSUE THREAD

**Issue by fablanglet** [serverless-tencent/serverless-tencent-tools#16]
I got this issue with serverless@1.67.2
```javascript
/usr/local/lib/node_modules/serverless/node_modules/serverless-tencent-tools/sdk/debug/lib/wshub-client/index.js:88
var __spreadArrays =
^^^

SyntaxError: Unexpected token var
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

10min ago, it was a different:

```javascript
 /usr/lib/node_modules/serverless/node_modules/serverless-tencent-tools/sdk/debug/lib/wshub-client/index.js:87
   }
   ^
 SyntaxError: Unexpected token '}'
     at wrapSafe (internal/modules/cjs/loader.js:1072:16)
     at Module._compile (internal/modules/cjs/loader.js:1122:27)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
     at Module.load (internal/modules/cjs/loader.js:1002:32)
     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
     at Module.require (internal/modules/cjs/loader.js:1044:19)
     at require (internal/modules/cjs/helpers.js:77:18)
     at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/serverless-tencent-tools/sdk/debug/lib/client.js:1:30)
     at Module._compile (internal/modules/cjs/loader.js:1158:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

**Comment by sanjay-zymr** [comment]
Facing same issue. blocking serverless.

**Comment by sitanshu-zymr** [comment]
Yes facing same issue, We are blocked.

**Comment by tinafangkunding** [comment]
@anycodes can you please help with it?

**Comment by RomkaSk** [comment]
The same problem =(
<img width="738" alt="Снимок экрана 2020-04-08 в 13 22 21" src="https://user-images.githubusercontent.com/11800834/78773955-a054ea00-799c-11ea-97f2-51a65f89025d.png">

**Comment by VivekSharma-zymr** [comment]
@yugasun @syzh @wescai @medikoo Currently we are blocked with this, Can you please check and solve this issue.

> **ERROR   2020-04-08 15:35:40      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  4528  100  4528    0     0  17687      0 --:--:-- --:--:-- --:--:-- 17687/code/node_modules/serverless-tencent-tools/sdk/debug/lib/wshub-client/index.js:88
ERROR   2020-04-08 15:35:40    var __spreadArrays =
ERROR   2020-04-08 15:35:40    ^^^
ERROR   2020-04-08 15:35:40    
ERROR   2020-04-08 15:35:40    SyntaxError: Unexpected token var
ERROR   2020-04-08 15:35:40        at new Script (vm.js:79:7)
ERROR   2020-04-08 15:35:40        at createScript (vm.js:251:10)
ERROR   2020-04-08 15:35:40        at Object.runInThisContext (vm.js:303:10)
ERROR   2020-04-08 15:35:40        at Module._compile (internal/modules/cjs/loader.js:657:28)
ERROR   2020-04-08 15:35:40        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
ERROR   2020-04-08 15:35:40        at Module.load (internal/modules/cjs/loader.js:599:32)
ERROR   2020-04-08 15:35:40        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
ERROR   2020-04-08 15:35:40        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
ERROR   2020-04-08 15:35:40        at Module.require (internal/modules/cjs/loader.js:637:17)
ERROR   2020-04-08 15:35:40        at require (internal/modules/cjs/helpers.js:22:18)
ERROR   2020-04-08 15:35:40    npm ERR! code ELIFECYCLE**

**Comment by anycodes** [comment]
OK, I have updated this package. I am sorry for this error. 
I don't know why the code was incorrectly formatted. I need to further investigate the cause. At present, the previous version has been overwritten and can be used. I'm sorry about this.

https://www.npmjs.com/package/serverless-tencent-tools/v/1.0.14

Now, you could reupdate the serverless-framework.
